spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management_system
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


spring.security.user.name=admin
spring.security.user.password=1234

jwt.secret=VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yU3ByaW5nQm9vdDM=
jwt.expiration=86400000

#superBasepasswowwd: pCMePxrIav5fX6CM