spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management_system
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true


spring.security.user.name=admin
spring.security.user.password=1234

jwt.secret=7H8DkP2LmQ9XvA5RtZ1NsF6YwE3UcJ8MbG4HpK7DxR2QaL9Vm
jwt.expiration=86400000
